### ISSUE TITLE
LSTMDAE

### ISSUE THREAD

**Issue by tallbf** [WuLoli/LSTMDAE#1]
I read with great interest your paper and I tried to run the code that you uploaded with no success. I'm new to python and I ran into reshaping and a conversion from strings to integers issues. I tried it on atom as well as on colab with all giving me the same errors. Python 3.6.9 and a downgraded version of tensorflow (1.14) didn't help.  below are the errors that I'm getting:

ValueError                                Traceback (most recent call last)
<ipython-input-16-de7adb4ec8d3> in <module>()
      6 X_test = np.moveaxis(X_test, 1, 2)
      7 
----> 8 X_train = get_amp_phase(X_train)
      9 X_validation = get_amp_phase(X_validation)
     10 X_test = get_amp_phase(X_test)
- ValueError: cannot reshape array of size 220000 into shape (1,128)

______________________________________________________________________________________

ValueError                                Traceback (most recent call last)
<ipython-input-14-4537e9b94ff8> in <module>()
     16     print(ite)
     17     history = model.fit(x = X_train,
---> 18                         y = [X_train, tf.keras.utils.to_categorical(Y_train[:, 0])],
     19                         validation_data = (X_validation, [X_validation, tf.keras.utils.to_categorical(Y_validation[:, 0])]),
     20                         batch_size = 128,
- ValueError: invalid literal for int() with base 10: 'AM-DSB'

**Comment by WuLoli** [comment]
Thanks for pointing it out! I just made a change to the data pre-processing part of the code. You should be able to run the code now. Let me know if you have any other questions.
