### ISSUE TITLE
Quetion about the dataset

### ISSUE THREAD

**Issue by vincentxiaotang** [WuLoli/LSTMDAE#2]
Hello，how can I get the NormalClasses.hdf5 file,  and the class labels in your code   are  classes = ['32PSK',
             '16APSK',
             '32QAM',
             'FM',
             'GMSK',
             '32APSK',
             'OQPSK',
             '8ASK',
             'BPSK',
             '8PSK',
             'AM-SSB-SC',
             '4ASK',
             '16PSK',
             '64APSK',
             '128QAM',
             '128APSK',
             'AM-DSB-SC',
             'AM-SSB-WC',
             '64QAM',
             'QPSK',
             '256QAM',
             'AM-DSB-WC',
             'OOK',
             '16QAM']
but are 'OOK, 4ASK, 8ASK, BPSK, QPSK, 8PSK, 16PSK, 32PSK, 16APSK, 32APSK, 64APSK, 128APSK, 16QAM, 32QAM, 64QAM, 128QAM,
256QAM, AM-SSB-WC, AM-SSB-SC, AM-DSB-WC, AM-DSB-SC, FM, GMSK, OQPSK' in 《Over-the-Air Deep Learning Based Radio
Signal Classification》. Is there a change in that?

**Comment by WuLoli** [comment]
You can get the datasets from https://www.deepsig.ai/datasets. When I downloaded the dataset, the classes were those I listed in my code. Note that the classes you listed here from  "Over-the-Air Deep Learning Based Radio Signal Classification" are a subset of the classes I listed in my code. 

You can select those normal classes from the dataset and generate NormalClasses.hdf5 by yourself.
